### ISSUE TITLE
ifconfig is depraved

### ISSUE THREAD

**Issue by ziruizhuang** [fishinbox/compass-core#1]
during installation the script uses a common tool ifconfig to determine certain network information.
However, unfortunately the ifconfig is depraved and stopped developing a long  time ago, as well as the fact that since CentOS 7 it is not inside the default installation packages.

As a result, the installation scripts are broke

**Comment by ziruizhuang** [comment]
#2

**Comment by pangxudong** [comment]
I have to write the name of nic when start installation, that way can make it success.
